spring:
  datasource:
    url: "jdbc:h2:./taskmgr"
    username: ""
    password: ""

  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true

  jpa:
    show-sql: true